# Generated by Django 5.1.3 on 2024-12-22 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200)),
                ('event_subhead', models.CharField(blank=True, max_length=300, null=True)),
                ('event_tag', models.CharField(choices=[('General', 'General'), ('Organizational', 'Organizational')], default='General', max_length=20)),
                ('event_venue', models.CharField(blank=True, max_length=200, null=True)),
                ('needs_attendance', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
            ],
            options={
                'db_table': 'Event',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_text', models.TextField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSpan',
            fields=[
                ('attendance_span_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='event_calendar.event')),
            ],
            options={
                'db_table': 'Attendance_Span',
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('participation_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_state', models.CharField(choices=[('Absent', 'Absent'), ('Present', 'Present'), ('Partial Present', 'Partial Present')], default='Absent', max_length=20)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_participation', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='event_calendar.event')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Participation',
                'ordering': ['event_id'],
                'unique_together': {('user_id', 'event_id')},
            },
        ),
    ]
